# Generated by Django 4.2.11 on 2026-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/no-image.webp', upload_to='gallery'),
        ),
    ]
